Update assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -3,22 +3,65 @@ mkdir /opt/app-root/moodledata
 #chown -R apache. /opt/app-root/moodledata
 chmod -R 777 /opt/app-root/moodledata
 
-#!/bin/bash
-mv .  mv /opt/app-root/moodledata/
+##################################################
+set -e
 
+source ${PHP_CONTAINER_SCRIPTS_PATH}/common.sh
 
-   # mv . * $HOME/.
-    
-    # mv  . $HOME/.
+shopt -s dotglob
+echo "---> Installing application source..."
+mv /tmp/src/* ./
 
+# Fix source directory permissions
+fix-permissions ./
+fix-permissions ${HTTPD_CONFIGURATION_PATH}
+# Change the npm registry mirror if provided
+if [ -n "$NPM_MIRROR" ]; then
+        npm config set registry $NPM_MIRROR
+fi
 
-#mover el moodle
-#mv /tmp/s2i/src $HOME/src
+if [ -f composer.json ]; then
+  echo "Found 'composer.json', installing dependencies using composer.phar... "
 
-# build application artifacts
-pushd ${HOME}
-make all
+  # Install Composer
+  TEMPFILE=$(mktemp)
+  RETRIES=6
+  for ((i=0; i<$RETRIES; i++)); do
 
-# install the artifacts
-make install
-popd
+    if [ -z "$COMPOSER_INSTALLER" ]; then
+      export COMPOSER_INSTALLER="https://getcomposer.org/installer"
+    fi
+
+    echo "Downloading $COMPOSER_INSTALLER, attempt $((i+1))/$RETRIES"
+    curl -o $TEMPFILE $COMPOSER_INSTALLER && break
+    sleep 10
+  done
+  if [[ $i == $RETRIES ]]; then
+    echo "Download failed, giving up."
+    exit 1
+  fi
+  php <$TEMPFILE
+
+  if [ "$(ls -a /tmp/artifacts/ 2>/dev/null)" ]; then
+    echo "Restoring build artifacts"
+    mv /tmp/artifacts/* $HOME/
+  fi
+
+  # Change the repo mirror if provided
+  if [ -n "$COMPOSER_MIRROR" ]; then
+    ./composer.phar config -g repositories.packagist composer $COMPOSER_MIRROR
+  fi
+
+  # Install App dependencies using Composer
+  ./composer.phar install --no-interaction --no-ansi --optimize-autoloader $COMPOSER_ARGS
+
+  if [ ! -f composer.lock ]; then
+    echo -e "\nConsider adding a 'composer.lock' file into your source repository.\n"
+  fi
+fi
+
+# post-assemble files
+process_extending_files ./php-post-assemble/ ${PHP_CONTAINER_SCRIPTS_PATH}/post-assemble/
+
+# Fix source directory permissions
+fix-permissions ./
